package com.paymentgateway.fraud.entity;

import com.paymentgateway.common.enums.RiskLevel;
import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Persistent record of a fraud evaluation for a single payment transaction.
 *
 * <p>Each row captures the full context of the fraud analysis: the composite risk score,
 * the individual rules that fired, the automated recommendation, and (optionally) any
 * manual review decision made by a fraud analyst.
 *
 * <h3>Lifecycle</h3>
 * <ol>
 *   <li>Created automatically when the fraud engine evaluates a transaction.</li>
 *   <li>If the risk level is HIGH or CRITICAL, the record is marked {@code blocked = true}.</li>
 *   <li>A fraud analyst can later approve or reject the transaction via the REST API,
 *       which updates {@code reviewedBy}, {@code reviewedAt}, and {@code blocked}.</li>
 * </ol>
 */
@Entity
@Table(name = "fraud_records", indexes = {
        @Index(name = "idx_fraud_transaction_id", columnList = "transactionId", unique = true),
        @Index(name = "idx_fraud_risk_level", columnList = "riskLevel"),
        @Index(name = "idx_fraud_blocked", columnList = "blocked"),
        @Index(name = "idx_fraud_merchant_id", columnList = "merchantId"),
        @Index(name = "idx_fraud_created_at", columnList = "createdAt")
})
@EntityListeners(AuditingEntityListener.class)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class FraudRecord {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique transaction identifier from the Payment Service. */
    @Column(nullable = false, unique = true, length = 64)
    private String transactionId;

    /** Merchant-facing order reference. */
    @Column(length = 64)
    private String orderId;

    /** The merchant that initiated the payment. */
    @Column(nullable = false)
    private Long merchantId;

    /** Transaction amount in the original currency. */
    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    /**
     * Composite risk score from 0 (safe) to 100 (critical fraud).
     * Computed by summing individual rule scores and capping at 100.
     */
    @Column(nullable = false)
    private Integer riskScore;

    /** Risk classification derived from the composite score. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private RiskLevel riskLevel;

    /**
     * Comma-separated names of all fraud rules that fired for this transaction.
     * Example: {@code "HIGH_AMOUNT,VELOCITY_CHECK,GEO_MISMATCH"}
     */
    @Column(length = 2000)
    private String triggeredRules;

    /** Human-readable recommendation generated by the fraud engine. */
    @Column(length = 500)
    private String recommendation;

    /** Whether the transaction was blocked (auto-blocked or manually rejected). */
    @Column(nullable = false)
    private Boolean blocked;

    /** Username or ID of the analyst who manually reviewed this record. */
    @Column(length = 100)
    private String reviewedBy;

    /** Timestamp of the manual review decision. */
    private LocalDateTime reviewedAt;

    /** Timestamp when this record was first created (set automatically by JPA auditing). */
    @CreatedDate
    @Column(nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
